### ISSUE TITLE
www.splittercontainer.eu is not secure

### ISSUE THREAD

**Issue by jurrejansen** [Whale-Agency/splitter#1]
Hi @DonKoko 

Could you assist here when you have a moment?

![Screenshot 2023-01-05 at 13 41 39](https://user-images.githubusercontent.com/76112272/210783265-411dc16e-9884-48a3-867c-13922aa9ed94.jpg)

I think we have VPS / Vimexx hosting for this but I can not request a certificate via Directadmin. I'm guessing this has to be done via the Vimexx environment?

**Comment by carlosvirreira** [comment]
as far as I remember, Splitter is hosted on the VPS of Misti.

**Comment by DonKoko** [comment]
@jurrejansen there is already a SSL it seems. I re-generated it just in case.
