### ISSUE TITLE
Product page

### ISSUE THREAD

**Issue by carlosvirreira** [Whale-Agency/splitter#14]
Split Color & Finishing into two attrributes

**Comment by jurrejansen** [comment]
@carlosvirreira this is done. However there is this thing that the price only starts updating after the user has chosen an option for both of the attributes. A default variant is set.

https://user-images.githubusercontent.com/76112272/218521751-5f183b98-22a8-4877-9acc-21e1668d3526.mov

ChatGPT is saying to add some custom javascript. 

Did a little research. We may want to wait until we have a site plan before starting to debug this.

https://discourse.webflow.com/t/variations-prices-not-being-updated/170859

![Screenshot 2023-02-13 at 17 54 32](https://user-images.githubusercontent.com/76112272/218522219-6ef0e2bb-94b4-4347-b740-66cda6500130.jpg)
