### ISSUE TITLE
Clicking on the heading texts in 'Featured posts' section doesn't link you to post. You have to click right next to them in order for it to work

### ISSUE THREAD

**Issue by jurrejansen** [Whale-Agency/splitter#17]
Didn't notice this when testing.

https://user-images.githubusercontent.com/76112272/220585239-22346527-7817-4fd6-90da-da00c5bee237.mov

**Comment by DonKoko** [comment]
Yeah i dont understand what is happening. I just see the mouse hovering and clicking.

EDIT: NVM, saw your description.

**Comment by DonKoko** [comment]
@jurrejansen solved. Please test and close if all is good.
