### ISSUE TITLE
Click on hover + Click to page functionality

### ISSUE THREAD

**Issue by jurrejansen** [Whale-Agency/splitter#5]
Hi @DonKoko 

Could you help me out with this featured updates section when you have the time. At some point you were working on the custom code but had to focus on something else. Just holla.

![image](https://user-images.githubusercontent.com/76112272/214330107-36868166-b651-4d12-aa39-d146192e3312.png)

**Comment by carlosvirreira** [comment]
Want to demo the site to Jan, do you think we can achieve to look into this potentially this week  @DonKoko ?

**Comment by DonKoko** [comment]
@carlosvirreira Yes, i can do it tomorrow. Just have to figure out how as this thing that we did is not working.

**Comment by DonKoko** [comment]
@jurrejansen pls test. Should be good now.
