### ISSUE TITLE
make cart button clickable

### ISSUE THREAD

**Issue by carlosvirreira** [Whale-Agency/splitter#7]
perhaps this works on your browser, but in Safari it does not. 

https://splitter-containers.webflow.io

![Screenshot 2023-02-06 at 14 01 24](https://user-images.githubusercontent.com/12449255/216977963-e020f42a-d320-44b7-9104-deae733f1a84.png)

Clicking on the '1' I would expect for the sidebar to open.

**Comment by jurrejansen** [comment]
was some z-index issue, fixed
